name: Monthly Opening Data Update

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 on the 1st of every month

jobs:
  update-openings:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-chess pandas

      - name: Run opening data ingestion script
        run: python openings_ingestor.py

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update monthly opening data"
          file_pattern: api/*.json