# .github/workflows/update-data.yml
name: Update Chess Data

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes. Change as needed.

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install libsql-client

      - name: Run data generation script
        env:
          TURSO_URL: ${{ secrets.TURSO_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        run: python generate_json.py # Assumes generate_json.py is in the root

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update chess data"
          file_pattern: api/*.json