name: Update Chess Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-chess pandas

      - name: Run data generation script
        run: python generate_json.py

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update chess data"
          file_pattern: api/*.json
